/**
 * AI 模型目录
 */
import type { AIModel } from '@/shared/types';

export const AI_MODELS: AIModel[] = [
  // OpenAI GPT-4.5 (2025)
  {
    id: 'gpt-4.5',
    name: 'GPT-4.5',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI GPT-4.5，2025年发布，多模态大模型',
    features: ['视觉理解', '高级推理', '代码生成', '200K上下文'],
    tokenLimit: 200000,
    isPro: true,
    contextWindow: 200000,
    pricing: { input: 0.01, output: 0.03, unit: '1K tokens' },
  },
  // Anthropic Claude 4 (2025)
  {
    id: 'claude-4-sonnet',
    name: 'Claude 4 Sonnet',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic Claude 4 Sonnet，2025年发布，平衡性能与速度',
    features: ['深度分析', '视觉理解', '长文本处理', '200K上下文'],
    tokenLimit: 200000,
    contextWindow: 200000,
    pricing: { input: 0.003, output: 0.015, unit: '1K tokens' },
  },
  {
    id: 'claude-4-opus',
    name: 'Claude 4 Opus',
    provider: 'anthropic',
    category: ['text', 'code', 'image'],
    description: 'Anthropic Claude 4 Opus，2025年发布，最强大模型',
    features: ['深度分析', '视觉理解', '长文本处理', '200K上下文'],
    tokenLimit: 200000,
    isPro: true,
    contextWindow: 200000,
    pricing: { input: 0.015, output: 0.075, unit: '1K tokens' },
  },
  // Google Gemini 2.0 (2025)
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    category: ['text', 'code', 'image', 'video'],
    description: 'Google Gemini 2.0 Flash，新一代多模态模型，支持视频分析',
    features: ['多模态分析', '视频理解', '长文本处理', '2M上下文'],
    tokenLimit: 2000000,
    contextWindow: 2000000,
    pricing: { input: 0.00035, output: 0.00105, unit: '1K tokens' },
  },
  {
    id: 'gemini-2.0-pro',
    name: 'Gemini 2.0 Pro',
    provider: 'google',
    category: ['text', 'code', 'image', 'video'],
    description: 'Google Gemini 2.0 Pro，最强大多模态模型',
    features: ['多模态分析', '视频理解', '长文本处理', '2M上下文'],
    tokenLimit: 2000000,
    isPro: true,
    contextWindow: 2000000,
    pricing: { input: 0.0035, output: 0.0105, unit: '1K tokens' },
  },
  // 百度模型
  {
    id: 'ernie-4',
    name: 'ERNIE 4.0',
    provider: 'baidu',
    category: ['text', 'code'],
    description: '百度最新自然语言理解模型',
    features: ['中文优化', '知识图谱', '对话能力'],
    tokenLimit: 8000,
    contextWindow: 8000,
    pricing: { input: 0.004, output: 0.012, unit: '1K tokens' },
  },
  {
    id: 'ernie-speed',
    name: 'ERNIE Speed',
    provider: 'baidu',
    category: ['text'],
    description: '轻量级高速模型',
    features: ['快速响应', '成本优化'],
    tokenLimit: 8000,
    contextWindow: 8000,
    pricing: { input: 0.001, output: 0.003, unit: '1K tokens' },
  },
  // 阿里模型
  {
    id: 'qwen-max',
    name: 'Qwen Max',
    provider: 'alibaba',
    category: ['text', 'code', 'image'],
    description: '通义千问最强模型',
    features: ['中文优化', '多模态', '长文本'],
    tokenLimit: 32000,
    isPro: true,
    contextWindow: 32000,
    pricing: { input: 0.004, output: 0.012, unit: '1K tokens' },
  },
  {
    id: 'qwen-plus',
    name: 'Qwen Plus',
    provider: 'alibaba',
    category: ['text', 'code'],
    description: '高性价比模型',
    features: ['平衡性能', '中文优化'],
    tokenLimit: 32000,
    contextWindow: 32000,
    pricing: { input: 0.0008, output: 0.002, unit: '1K tokens' },
  },
  // 智谱模型
  {
    id: 'glm-4',
    name: 'GLM-4',
    provider: 'zhipu',
    category: ['text', 'code'],
    description: '智谱最新大模型',
    features: ['中文理解', '代码生成'],
    tokenLimit: 128000,
    contextWindow: 128000,
    pricing: { input: 0.001, output: 0.003, unit: '1K tokens' },
  },
  // 讯飞模型
  {
    id: 'spark-v3.5',
    name: '讯飞星火 V3.5',
    provider: 'iflytek',
    category: ['text', 'code'],
    description: '科大讯飞认知大模型',
    features: ['中文优化', '多轮对话'],
    tokenLimit: 8000,
    contextWindow: 8000,
    pricing: { input: 0.002, output: 0.006, unit: '1K tokens' },
  },
  // 腾讯模型
  {
    id: 'hunyuan-pro',
    name: '腾讯混元 Pro',
    provider: 'tencent',
    category: ['text', 'code'],
    description: '腾讯混元大模型',
    features: ['中文优化', '多模态'],
    tokenLimit: 32000,
    contextWindow: 32000,
    pricing: { input: 0.003, output: 0.009, unit: '1K tokens' },
  },
  // ===== 2026 年新模型 =====
  // MiniMax 模型
  {
    id: 'minimax-m2.5',
    name: 'MiniMax M2.5',
    provider: 'minimax',
    category: ['text', 'code'],
    description: 'MiniMax M2.5 大模型，2026年2月发布，支持超长上下文',
    features: ['超长上下文', '中文优化', '高性价比'],
    tokenLimit: 100000,
    contextWindow: 100000,
    pricing: { input: 0.01, output: 0.03, unit: '1K tokens' },
  },
  // 月之暗面模型
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5',
    provider: 'moonshot',
    category: ['text', 'code', 'image'],
    description: '月之暗面 Kimi K2.5，2026年发布，支持多模态理解',
    features: ['多模态理解', '长上下文', '代码生成'],
    tokenLimit: 200000,
    contextWindow: 200000,
    pricing: { input: 0.012, output: 0.036, unit: '1K tokens' },
  },
  // 字节豆包模型
  {
    id: 'doubao-2.0',
    name: '豆包 2.0',
    provider: 'bytedance',
    category: ['text', 'code', 'image'],
    description: '字节跳动豆包 2.0，2026年发布，高性能多模态模型',
    features: ['多模态', '快速响应', '中文优化'],
    tokenLimit: 128000,
    contextWindow: 128000,
    pricing: { input: 0.005, output: 0.015, unit: '1K tokens' },
  },
  // 阿里 Qwen 2.5
  {
    id: 'qwen-2.5',
    name: 'Qwen 2.5',
    provider: 'alibaba',
    category: ['text', 'code', 'image'],
    description: '阿里通义千问 2.5，2026年发布，全面升级',
    features: ['多模态', '长上下文', '代码生成'],
    tokenLimit: 32000,
    contextWindow: 32000,
    pricing: { input: 0.006, output: 0.018, unit: '1K tokens' },
  },
  // 百度 ERNIE 4.0 (2026)
  {
    id: 'ernie-5.0',
    name: 'ERNIE 5.0',
    provider: 'baidu',
    category: ['text', 'code', 'image'],
    description: '百度 ERNIE 5.0，2026年发布，全面升级',
    features: ['中文优化', '知识图谱', '多模态'],
    tokenLimit: 128000,
    contextWindow: 128000,
    pricing: { input: 0.008, output: 0.024, unit: '1K tokens' },
  },
  // 智谱 GLM-5
  {
    id: 'glm-5',
    name: 'GLM-5',
    provider: 'zhipu',
    category: ['text', 'code', 'image'],
    description: '智谱 GLM-5，2026年2月发布，全面升级',
    features: ['中文理解', '代码生成', '多模态'],
    tokenLimit: 128000,
    contextWindow: 128000,
    pricing: { input: 0.005, output: 0.015, unit: '1K tokens' },
  },
  // 字节图像生成 - Seedream 5.0
  {
    id: 'seedream-5.0',
    name: 'Seedream 5.0',
    provider: 'bytedance',
    category: ['image'],
    description: '字节 Seedream 5.0，2026年2月10日发布，2K直出,4K AI增强,控制笔刷',
    features: ['2K直出', '4K AI增强', '控制笔刷', '图像生成'],
    tokenLimit: 4096,
    contextWindow: 4096,
    pricing: { input: 0.01, output: 0.05, unit: '1K tokens' },
  },
  // 快手可灵
  {
    id: 'kling-1.6',
    name: '可灵 1.6',
    provider: 'kling',
    category: ['image', 'video'],
    description: '快手可灵 1.6，2026年发布，图像+视频生成',
    features: ['图像生成', '视频生成', 'AI增强'],
    tokenLimit: 4096,
    contextWindow: 4096,
    pricing: { input: 0.02, output: 0.1, unit: '1K tokens' },
  },
  // 快手可灵 3.0
  {
    id: 'kling-3.0',
    name: '可灵 3.0',
    provider: 'kling',
    category: ['image', 'video'],
    description: '快手可灵 3.0 Omni，2026年发布，图像理解和物理世界模拟增强，叙事感增强',
    features: ['图像生成', '视频生成', '多镜头', '15秒时长', '原生音视频同步'],
    tokenLimit: 4096,
    contextWindow: 4096,
    pricing: { input: 0.015, output: 0.08, unit: '1K tokens' },
  },
  // 生数 Vidu
  {
    id: 'vidu-2.0',
    name: 'Vidu 2.0',
    provider: 'bytedance',
    category: ['image', 'video'],
    description: '生数 Vidu 2.0，2026年发布，图像+视频生成',
    features: ['图像生成', '视频生成', 'AI增强'],
    tokenLimit: 4096,
    contextWindow: 4096,
    pricing: { input: 0.015, output: 0.08, unit: '1K tokens' },
  },
  // 字节 Seedance 2.0
  {
    id: 'seedance-2.0',
    name: 'Seedance 2.0',
    provider: 'bytedance',
    category: ['video'],
    description: '字节 Seedance 2.0，2026年2月12日发布，文本/图片/视频输入,镜头保持一致',
    features: ['文本生成视频', '图片生成视频', '视频生成视频', '镜头一致性'],
    tokenLimit: 4096,
    contextWindow: 4096,
    pricing: { input: 0.05, output: 0.2, unit: '1K tokens' },
  },
];
